modLoader = "javafml"
loaderVersion = "[35,)"
license = "All Rights Reserved"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "Ocelot & Jackson"
description = '''
Example Description
'''

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3,)"
ordering = "NONE"
side = "BOTH"